#!/bin/bash
# Export some ENV variables so you don't have to type anything
export AWS_ACCESS_KEY_ID="AWSKEYAWSKEY"
export AWS_SECRET_ACCESS_KEY="AWSSECRETKEYAWSSECRETKEY"
export PASSPHRASE="ENCRYPTIONPASSPHRASE"

# The S3 destination followed by bucket name
DEST="s3+http://my-bucket-name/folder"

# Your GPG key 
#GPG_KEY=YOUR_GPG_KEY
##COMMENT OUT GPG_KEY AND UNCOMMENT "export PASSPHRASE" to enable backup just with password

#duplicity list-current-files --timeout=2400 --tempdir /tmp/dupltemp --num-retries=500 -t 6M ${DEST}
if [ $# -lt 3 ]; then echo "Usage $0 <date> <file> <restore-to>"; exit; fi

duplicity -v9  --s3-use-new-style \
    --s3-european-buckets \
    --restore-time $1 \
    --file-to-restore $2 \
    ${DEST} $3

# Reset the ENV variables. Don't need them sitting around
unset AWS_ACCESS_KEY_ID
unset AWS_SECRET_ACCESS_KEY
unset PASSPHRASE
